### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by milandzuris** [YorkshireIoT/ha-google-fit#12]
### System Health details

Hi and thank you so much for this integration, whats the Update Interval for Sensors?, and im have question whats the Active Minutes daily? its old move time?
![image](https://user-images.githubusercontent.com/42905545/229361645-e77875d7-971c-4841-96f6-f8dab883037f.png)

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

*

### Reproduction steps

*

### Debug logs

```text
*
```

**Comment by YorkshireIoT** [comment]
Hi @milandzuris,

Here are the answers to your questions

### Update Interval
The update is interval is currently 1 minute as defined here: https://github.com/YorkshireIoT/ha-google-fit/blob/main/custom_components/google_fit/coordinator.py#L39

I did consider making it configurable but there doesn't actually seem to be any benefit to that. Google Fit itself is much slower at syncing your data (I've noticed it seems to be every hour for me).

### Active Daily Mintues
Yes, you're right that this is the same as Move Minutes in the old sensor. It's described in more detail here: https://developers.google.com/fit/datatypes/activity#move_minutes

I called it active minutes because the API data source ID is `active_minutes` and so it makes the code a lot clearer to stick with that.

It's probably worth updating the README to add links to the Google docs where each sensor is explained.
